### ISSUE TITLE
enable `MatAlgebra{<:NCRingElem}`?

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#1035]
I don't think a new type for matrices over non-comutative ring is in order.
pros:
- we can have matrices of matrices
- we can have matrices of ncpoly's
- ...

cons:
- figuring out which parts of the current matrix code can be shared with non-comutative rings is a bit of work.

**Comment by thofma** [comment]
I am in favor of this proposal. By coincidence I was in need of this today.

I agree that we do not need to go down the `NCPoly/Poly` route, since there it mattered because `NCPoly <: NCRingElem` and `Poly <: RingElem`. For matrices this is irrelevant, since it will be `<: NCRingElem` anyway.

I would just change all signatures to `MatrixElem{<: RingElem}` and then change as little as possible to make the interface work.
