### ISSUE TITLE
non-coersion problems

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/AbstractAlgebra.jl#1059]
AbstractAlgebra is bad:
```
julia> using AbstractAlgebra

julia> _, x = PolynomialRing(ZZ, "x"); x*QQ(2)
ERROR: MethodError: no method matching setcoeff!(::AbstractAlgebra.Generic.Poly{BigInt}, ::Int64, ::Rational{BigInt})

julia> _, (x,) = PolynomialRing(ZZ, ["x"]); x*QQ(2)
2*x
```

Nemo is good:
```
julia> using Nemo

julia> _, x = PolynomialRing(ZZ, "x"); x*QQ(2)
ERROR: Cannot promote to common type

julia> _, (x,) = PolynomialRing(ZZ, ["x"]); x*QQ(2)
ERROR: Cannot promote to common type
```

**Comment by wbhart** [comment]
I am not sure what the solution should be here.

In Julia we have ZZ(QQ(2)) == ZZ(2)

This is relied upon in the LaurentPoly module, for example we have the following test:

```
      Z, z = LaurentPolynomialRing(ZZ, "z")
      Q, q = LaurentPolynomialRing(QQ, "q")

      @test change_base_ring(ZZ, q) == z
```

If I make the changes to cause an error to be raised when the second example above is run, this test fails.

It's also quite hard to come up with a set of adhoc multiplication, divexact and equality testing operators that covers all cases if we disallow the example above. The reason has to do with the fact that we are using Julia types for ZZ and QQ in AbstractAlgebra.

I think it might actually be easier to allow the coercion of elements of QQ that happen to be integers to ZZ consistently across the whole of AbstractAlgebra than to try and fix it in line with Nemo.

Either way there is virtually no hope of getting a nice error message like we have in Nemo since Julia promotion rules make this difficult.

As this doesn't affect Oscar, I think it is just too much trouble to fix.
