### ISSUE TITLE
in for Sets of MPoly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#111]
I am surprised to find that after

```
using AbstractAlgebra
R,v = PolynomialRing(ZZ,["x","y"]); x=v[1]
```

the output of 

`x in Set(gens(R))`

seems not to be deterministic, as the following example shows:

```
julia> for i=1:20 println(x in Set(gens(R))) end
false
false
false
false
false
false
true
false
false
false
true
false
false
true
false
false
false
false
false
false

```

I am not sure whether this behavior is indented or whether it is a bug in either Julia or AbstractAlgebra.

**Comment by wbhart** [comment]
I imagine sets only work for objects that have a hash defined and satisfy a
certain interface. It might also be to an attempt to construct something
from the type alone, which won't work with any AbstractAlgebra objects.

We simply have to look into whether this is a feature we can support or
not. Sometimes it's just not possible, either for mathematical reasons or
due to assumptions Julia makes about how objects are constructed (from
types, rather than parents).

>

**Comment by thofma** [comment]
The default hashing is not working properly for `MPoly` (it rarely does for custom mutable types). To be useful we must have that `f == g` implies `hash(f) == hash(g)`. But:

```julia
julia> hash(gens(R)[1])
0x808202b0ca0333a8

julia> hash(gens(R)[1])
0xec1f203060baa17e

julia> hash(gens(R)[1])
0xeb698aa1661f6b04

julia> hash(gens(R)[1])
0x20e6dff0f8e32b98
```

We need to extend `Base.hash` to `MPoly`.
