### ISSUE TITLE
Allow to specify a char 

### ISSUE THREAD

**Issue by alexjbest** [Nemocas/AbstractAlgebra.jl#124]
This is kinda dumb, but it can trip up a new user like me:

```
julia> R = PolynomialRing(K,'x')
ERROR: MethodError: no method matching PolynomialRing(::Nemo.FlintPadicField, ::Char)
```

If it's not difficult/bad for some reason allowing a char to be the name of a variable would be nice.

**Comment by wbhart** [comment]
Yeah, we could probably support that. There's also a request that we
support using a symbol as a variable name. The main issue with these
suggestions is that there already have to be many PolynomialRing functions,
due to the many different applications of polynomials, and this effectively
multiplies the number by 3.

Having said that, what you are asking does make some sense.
