### ISSUE TITLE
Change `poly_ring_type` to `dense_poly_ring_type`?

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#1289]
> Wouldn't it then make more sense to call it `dense_poly_ring_type`?

_Originally posted by @fingolfin in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1282#discussion_r1140601028_

**Comment by thofma** [comment]
On the other hand, we probably want to rename `dense_poly_type` to `poly_type` if I understand correctly?

**Comment by mgkurtz** [comment]
For reference: in our [notes for the big renaming](https://hackmd.io/0hrBHIUrRZG23xiZZ0NCEA#Rules-for-naming-types) we (actually it was @fieker, I think) said

> * If a type comes in sparse and dense variants, then call the dense type T and the sparse one SparseT

The reasoning (as far as I recollect) was, that “dense” is the default and thus does not need to be spelled out.

**Comment by fingolfin** [comment]
My main concern is that `dense_poly_type` and `poly_ring_type` should be synced. Which way we go I don't mind very much. Though of course `dense_poly_type` has been around for a long time, so we'd have to at least `@alias` it for the time being.


Of course we also have `mpoly_ring_type` and `mpoly_type`. Should that then be `sparse_poly*_type`? Or conversely should `poly_type` become `upoly_type`? Or maybe it should be spelled out `multivariate_poly*_type` and `univariate_poly*_type`?

I don't want to overcomplicate it, just saying there are lots of variants. So, here is what I would suggest, to keep work to a minimum for now: we rename `poly_ring_type` to `dense_poly_ring_type` to be consistent. This require minimal effort.

Then we can think about whether we want to rename these functions, and how, and then do it all at once, instead of piecemeal.
