### ISSUE TITLE
Coercing 1-D array into MatrixSpace now fails

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#148]
In Julia 1.0.0 the operation A' now returns a matrix of type Adjoint instead of the same type as the original matrix. The function transpose now returns a type Transpose. Therefore we can't use either of them to actually transpose in the implementation of the parent call R([1, 2, 3, 4, 5, 6, 7, 8, 9]) where R is a 3x3 matrix space.

**Comment by fieker** [comment]
On Wed, Sep 19, 2018 at 06:33:13AM -0700, wbhart wrote:
> In Julia 1.0.0 the operation A' now returns a matrix of type Adjoint instead of the same type as the original matrix. The function transpose now returns a type Transpose. Therefore we can't use either of them to actually transpose in the implementation of the parent call R([1, 2, 3, 4, 5, 6, 7, 8, 9]) where R is a 3x3 matrix space.
> 
> -- 
This is for Arrays, for our native matrices it is fine.
So "all" we need is to also accept Adjoint as well.

It would be cool if the julia people would at least KNOW what an adjoint
is rather than a hermitean transpose. I thought adjoint is when you
replace entries by the determinant of some sub matrix...

**Comment by thofma** [comment]
Fixed with https://github.com/Nemocas/AbstractAlgebra.jl/pull/150
