### ISSUE TITLE
Welcome message AbstractAlgebra

### ISSUE THREAD

**Issue by jarlebring** [Nemocas/AbstractAlgebra.jl#158]
Thanks for a nice work on this package. Is there any chance that you could remove the "Welcome to" message? We are using AbstractAlgebra as a part of a bigger project (NEP-PACK). We have a  dependency on PolynomialZeros which in turn depends on AbstractAlgebra. The welcome message appear for every user (and often it appears several times). It becomes quite a bit distracting for our users. Thanks!

**Comment by wbhart** [comment]
@thofma @fieker Do you have an opinion on this? I have no principal objection, other than it makes it slightly harder for us to determine what version we are working from. On the other hand, this info could be printed from Nemo or something, which would keep us happy.

**Comment by wbhart** [comment]
@fieker Seems reasonable to me. Would you be interested in supplying a PR, @jarlebring?

**Comment by wbhart** [comment]
I don't see why it cannot simply look for a file called quiet in the AbstractAlgebra Pkg.dir. If it's there, it doesn't print the message. Packages that....

Hmm, yes, I see the problem now.

**Comment by jarlebring** [comment]
>  if people are using our packages they should see the banner - otherwise they will never learn about our existence. We need the advertising I'd say...

I find this reasoning questionable for many reasons. Julia is built on many small packages. Is your package really in more need of advertisement than others. 

Also: the visibility AbstractAlgebra (currently) gets from our package just makes people annoyed, I think.  

But okay, I'm not a contributor to this project, and I just wanted to point your attention to how it looks from our perspective. Feel free to close this issue if you feel this is not in line with what you have in mind.

**Comment by fredrik-johansson** [comment]
I think the messages are a bad idea.

**Comment by kindlychung** [comment]
IMHO, usage is the best acknowledge you can find. Putting `AbstractAlgebra` under deps means a lot. Why get in the way of the user?

Imagine every julia package starts giving a welcome message...

**Comment by ChrisRackauckas** [comment]
IMO a better compromise is to make it part of the package build. Here's an example of that:

https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/82

Then it will show up during package add and updates (and you can set it up so it won't do it on updates). Packages do need a good way to inform users but IMO in `init` is too much.

**Comment by JeffreySarnoff** [comment]
It is your software and you are entitled to identify it as such as frequently as you like.  I agree with @ChrisRackauckas  that providing the banner when building (which can be done even if the only build action is to display the banner) provides a way to meet your desire without making the use of your work by other developers cumbersome with respect to the experience their users (who may be other developers) obtain.  As a practical matter, the package development that you do is so well-regarded by the community and unique in/to our package ecosystem that anyone utilizing the work is highly motivated to acknowledge the package and its authors.

**Comment by fieker** [comment]
On Sun, Sep 30, 2018 at 05:37:31PM -0700, Jeffrey Sarnoff wrote:
> It is your software and you are entitled to identify it as such as
> frequently as you like.  I agree with @ChrisRackauckas  that providing
> the banner when building (which can be done even if the only build
> action is to display the banner) provides a way to meet your desire
> without making the use of your work by other developers cumbersome
> with respect to the experience their users (who may be other
> developers) obtain.  As a practical matter, the package development
> that you do is so well-regarded by the community and unique in/to our
> package ecosystem that anyone utilizing the work is highly motivated
> to acknowledge the package and its authors.
> 
OK, here's the problem we need to solve. And, while the problem on our
community is known for > 15 years, we do not have any solution that
works.

Problem: authors need to get credit for their work - at least in the
academic environment that equates formal citations that I can show my
grant agency. (The stupidity of this metric is a different discussion)
I install e.g. your new package DiffEq since I plan to do a publication
using this. You install, quite likely, a number of packages
automatically, among them will be packages that are essential for the
functionality I need, others are merely conveninence or eye candy (or
required for other parts of the package that I don't need).
I do my work and now need to write the paper.
 I will cite julia and your package.
 Will I cite all dependencies? How will I know what to cite and what
 not?

Yes, I can ask for a Pkg.status() and get the complete list (very long),
look at build logs, ...
But all of this requires ME to be active. Experience shows this is not
going to happen. In fact, most articles will stop after julia and not
even cite your package.
Banner: I don't know if this works - but it reminds (or annoys) people
every time they start things up.
I'd probably opt for 
using Bla;
         =
will supress all banners (printing in init())
using Bla
         =
will print.
I personally would like to see (when not using a ;) a message
indicating success: Package loaded or similar. I could suppress it using
";"

So the problem is: how to get proper citations - and how to support
this on the infrastructure level in julia?

We discussed this among ourselves and it is possible that the banner
will disappear from AbstractAlgebra. However, the problem still stays -
and at least I still don't even see a solution.

**Comment by ChrisRackauckas** [comment]
> I will cite julia and your package. Will I cite all dependencies? How will I know what to cite and what
 not?

We keep a citation list with instructions:

http://juliadiffeq.org/citing.html

IMO that should be more formalized in Julia. xref https://github.com/JuliaLang/Pkg.jl/issues/212

**Comment by fieker** [comment]
On Mon, Oct 01, 2018 at 07:01:01AM -0700, Christopher Rackauckas wrote:
> > I will cite julia and your package. Will I cite all dependencies? How will I know what to cite and what
>  not?
> 
> We keep a citation list with instructions:
> 
> http://juliadiffeq.org/citing.html
> 
> IMO that should be more formalized in Julia. xref https://github.com/JuliaLang/Pkg.jl/issues/212

You're missing the point, that part is clear. But how do I, as a user,
figure out that I also should cite AbstractAlgebra?
DifferentialEquations is easy: I install it explicitly, so I am aware of
it. However the dependencies are hidden.

**Comment by fieker** [comment]
On Mon, Oct 01, 2018 at 07:01:01AM -0700, Christopher Rackauckas wrote:
> > I will cite julia and your package. Will I cite all dependencies? How will I know what to cite and what
>  not?
> 
> We keep a citation list with instructions:
> 
> http://juliadiffeq.org/citing.html
> 
I missed the long list, sorry.
But how do I, as a user, figure out which of them is relevant to the
computation I just did?
I am not at all critizising anyone or anything here, we had/have the
same problem, unsolved, for many years in Magma, Sage and any other
larger system that accumumlates useful features. I honestly do not know
how to deal with it...

**Comment by Datseris** [comment]
This is the approach I use to display crucial information: https://discourse.julialang.org/t/displaying-an-update-message/12577

They do not use a build script and they are displayed only on the first `using` statement. Not more. You can choose to display this message (or a new one) in every new release.

**Comment by StefanKarpinski** [comment]
For what it's worth, I think that printing this banner whenever someone uses your package is not a good idea. (Imagine if every package did this? I could arrange a demo version of Julia that does that. I don't think you would enjoy using it.) While the need to get credit in an academic setting is understandable, I don't think this is the way to go about it. For one thing, it's clearly annoying your users (hence this issue). The main thing the message causes is people to not to use your package—there is a conversation right now on Slack about people not using Nemo because of these messages. If some people are abandoning your software and talking about it then I would guess there are at least 100x that many people abandoning your software silently. I do not think that's the result you wanted. Since this package is open source, there's a very real danger that someone will make a fork which just removes the message and people will start using that instead.

**Comment by thofma** [comment]
We removed the banner and will release a new version soonish.
