### ISSUE TITLE
MPoly total_degree is incorrect and exceedingly inefficient

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#169]
The function doesn't work for the zero polynomial and there is no need to copy the exponent array or to take a maximum when the ordering is a degree ordering, since they are already sorted in order!

**Comment by heiderich** [comment]
What should `total_degree` return for a zero polynomial?

**Comment by wbhart** [comment]
By the way, it's a little hard to fix this until I finish my rewrite of MPoly. It's breathing, but it will still be some time before it is all working properly, and even longer before all the Nemo interfaces for multivariates in Flint are done and match MPoly. But we are getting there.

**Comment by heiderich** [comment]
Mathematically, often the degree function is not defined on zero. When it is, I have usually seen it being defined as $deg(0) = - \infty$, so that the extended function $deg : R \to Z \cup \{ -\infty \}$ also fulfills deg(fg) = deg(f) + deg(g) for all f and g (with a proper definition of the addition on $Z \cup \{ -\infty \}$).

Returning -1 would mean that this rule does not hold anymore for all ring elements. So I think - \infty would be more suitable. However I have only seen `Base.Inf64`, `Base.Inf32` and `Base.Inf16` to represent infinity in Julia, which are of type `Float64`, `Float32` and `Float16`, respectively. Using one of them would mean that the return value of `total_degree` would be different for non-zero polynomials and the zero polynomial.

Another option would be to return an error or something else indicating that this is not defined.

**Comment by fredrik-johansson** [comment]
Yes, -1 makes the relation to the length consistent, and it works nicely with integer types, so it is a good convention in a computational context.

**Comment by heiderich** [comment]
> E.g. if you take the degree of a polynomial in a variable that doesn't appear, it also has to return -1 if the whole polynomial is zero (but 0 if not).

What do you mean by "take the degree of a polynomial in a variable that doesn't appear" in this context? Are not we talking about total degrees?

Again, in my opinion deg(fg) = deg(f) + deg(g) should hold for all f and g such that all three degrees are defined. The choice deg(0) = -1 would break this.

**Comment by wbhart** [comment]
It doesn't matter if you talk about total degree or degree in a variable. Both could be fields returned by max_fields, depending on the ordering. And they will return 0.

The only value which would make your identity hold is -\infty, and that's not a machine int, so there's no way to do that.
