### ISSUE TITLE
polcoeff vs pol_length and normalise vs renormalize

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#17]
It is clear that we don't have a consistent naming convention. This is especially true in the power series.

Probably polcoeff should be pol_coeff and renormalize should be renormalise.

**Comment by wbhart** [comment]
On the other hand, Julia has getindex and setindex! which means if we follow suit we'd have getcoeff, setcoeff! (the latter of which we do have in AbstractAlgebra). So it's not too far from there to polcoeff.

Does anyone have a strong opinion about changing it? If not, I'll leave that one. It is already used a handful of times in Hecke too.

However, the second change might be more worthwhile. Trying to guess whether British or American English spelling is being used is tricky. I propose we stick to British English as a rule and change renormalize to renormalise in line with normalise used elsewhere. Nemo.renormalize! is used twice in Hecke, in Misc so it's not a big change. It's not used in Singular.jl or Oscar.jl.

I realise it is basically code churn and not urgent, but the earlier we fix this the less code we have to fix later. I'm happy to make the PR's. Any objections?

**Comment by thofma** [comment]
There is too much MATLAB baggage in the Base namespace. It is totally inconsistent. For example there is `set_zero_subnormals` (exported and document, so not something internal). I don't feel a strong urge to follow this "convention". Also, a few weeks ago we decided to go with `set_precision` instead of `setprec` etc.

I usually prefer American English, but it is fine with me to stick to British English. It is easy to add aliases.

**Comment by wbhart** [comment]
Could you clarify what you actually want for polcoeff. Not following the Julia "convention" is ambiguous, since there isn't one.

I'm not sure aliases are a good idea. It's not just the odd function name but also named arguments, field names, type names, Abstract types etc. It's a little hard to alias all these.

I do think it would be natural to pick one or the other convention on spelling. But if we have opposite preferences, maybe it is better to not insist on a convention. I couldn't find any convention for Sage or Magma (or rather Google could not).

**Comment by rfourquet** [comment]
FWIW, I also prefer American spelling as it's likely the most used in the Julia ecosystem.

**Comment by wbhart** [comment]
I'm happy to revize my preference and come to a compromize assuming everyone else can agree.

**Comment by wbhart** [comment]
I think I will close this particular ticket anyway. There's no convention worth following in either of the cases mentioned in the ticket. We can open additional tickets to discuss a general convention going forward if it is deemed worthwhile. Spending a week of work conforming all existing code seems like a waste of manpower in any event.

**Comment by thofma** [comment]
I am happy to leave `polcoeff` as is. FWIW, Magma tries to provide both. For example there is `IsNormalized` and `IsNormalised`.

**Comment by fieker** [comment]
On Thu, Oct 29, 2020 at 09:08:38AM -0700, wbhart wrote:
> Could you clarify what you actually want for polcoeff. Not following the Julia "convention" is ambiguous, since there isn't one.
> 
> I'm not sure aliases are a good idea. It's not just the odd function name but also named arguments, field names, type names, Abstract types etc. It's a little hard to alias all these.
> 
> I do think it would be natural to pick one or the other convention on spelling. But if we have opposite preferences, maybe it is better to not insist on a convention. I couldn't find any convention for Sage or Magma (or rather Google could not).

Magma, more or less systematically, supports both british (normalise)
and americal (normalize). This is a nightmare: conisder any
autocomplete, tab-completion feature. Unless extremely intelligent, it
can only ever complete up to the s/z.
We can vote or decide, but it should be ONE not both. I guess julia
leans towards american...

pol_coeff vs polcoeff: I thought, the rule of thumb is: a short first
word is connected directly, subsequent (or hard to read) gets
underscore....
isone vs push_term
isirreducible vs berlekamp_massey
cansolve vs cansolve_with_solution_and_nullspace (or so)

Aliases are difficult - we tried: NumberField = number_field 
But when you want to add a new method you need to add (or at least
needed) to the original, you cannot add to an alias.
Also methods and such will show the other name.

Second problem: aliases can, and tend to, backfire: in Magma
for a number field: MaximalOrder(K) = RingOfIntegers(K) = Integers(K) 
However, Integers() = RingOfIntegers() yields ZZ
MaximalOrder() an error...

Just because you want a (natural) alias in one context does not mean it
makes sense in other areas of math...

**Comment by fieker** [comment]
On Thu, Oct 29, 2020 at 09:33:58AM -0700, wbhart wrote:
> I'm happy to revize my preference and come to a compromize assuming everyone else can agree.
> 
Havin' fun, have you?

**Comment by wbhart** [comment]
I think it is actually can_solve. Of course this just reinforces how hard
things are to remember without a convention.

As for spelling, I was simply suggesting that we need not enforce a
convention, even if there be only one spelling for any given function/name,
whether it be American or British. It might be a bit hard to enforce, and
in any event seems like a major distraction at present to go and change all
existing spelling.

We also have the problem that we already use the Julia spelling of many
things, which is not necessarily consistent with any convention we might
pick.

At the very least, we could make a convention going forward, but leave
existing spellings/underscores alone for now, until we have more time to do
it consistently everywhere. I can live with American spelling I suppose. I
think we should draw the line at Americanisms though, such as "off of" and
so on. I suspect there are two types of journals: those that allow English
only and those that allow American as well.

**Comment by fieker** [comment]
On Fri, Oct 30, 2020 at 12:43:44AM -0700, wbhart wrote:
> I think it is actually can_solve. Of course this just reinforces how hard
> things are to remember without a convention.
> 
> As for spelling, I was simply suggesting that we need not enforce a
> convention, even if there be only one spelling for any given function/name,
> whether it be American or British. It might be a bit hard to enforce, and
> in any event seems like a major distraction at present to go and change all
> existing spelling.
> 
> We also have the problem that we already use the Julia spelling of many
> things, which is not necessarily consistent with any convention we might
> pick.
> 
> At the very least, we could make a convention going forward, but leave
> existing spellings/underscores alone for now, until we have more time to do
> it consistently everywhere. I can live with American spelling I suppose. I
> think we should draw the line at Americanisms though, such as "off of" and
> so on. I suspect there are two types of journals: those that allow English
> only and those that allow American as well.


...and the one allowing also denglish and other dialects...


But I agree: this is not a priority at all...
Lets drop this for now
> 
>
