### ISSUE TITLE
Field is no longer a Group

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#171]
```julia
julia> using AbstractAlgebra
[ Info: Recompiling stale cache file /home/kalmar/.julia/compiled/v1.0/AbstractAlgebra/b8V2b.ji for AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> typeof(GF(5))
AbstractAlgebra.GFField{Int64}

julia> ans <: AbstractAlgebra.Group
false

julia> supertype(typeof(GF(5)))
FinField

julia> supertype(ans)
AbstractAlgebra.Field

julia> supertype(ans)
AbstractAlgebra.Ring

julia> supertype(ans)
AbstractAlgebra.NCRing

julia> supertype(ans)
AbstractAlgebra.Set
```

moreover:
```julia
julia> AbstractAlgebra.versioninfo()
AbstractAlgebra version 0.1.4-dev
AbstractAlgebra: ERROR: UndefVarError: LibGit2 not defined
Stacktrace:
 [1] getproperty at ./sysimg.jl:13 [inlined]
 [2] versioninfo() at /home/kalmar/.julia/dev/AbstractAlgebra/src/AbstractAlgebra.jl:76
 [3] top-level scope at none:0
```
I'm at `e851e89249fc679d22248a20c612ae85b4459577`

**Comment by wbhart** [comment]
That's correct. Do you need it to be? Can you remind me of the application?

**Comment by thofma** [comment]
We could just do NCRing <: Group.

**Comment by wbhart** [comment]
Yes we could. But the logic here is that a ring is an additive group from the perspective of computation, but we use * for the operation in our existing groups. So from the perspective of computation, it's not a super useful identification. Fields obviously are a problem, since they are more meaningful as groups, but we can't just make them groups without making ring belong to group, hence the question about application.

**Comment by kalmarek** [comment]
I work with `SL(N,R)` which I implement as `MatrixSpace` and then define group by generators (elementary matrices). At the same time the same code is run for other (finitely presented) groups;

Where I need the identity, i.e. `G()` I tend to overload method with `R(1)` for Rings;
Now however things broke completely;

I also thought about
```julia
for (Gr, Elem) in [(:MltGrp, :MltGrpElem), (:AddGrp, :AddGrpElem)]
   @eval begin
      struct $Gr{T<:AbstractAlgebra.Ring} <: AbstractAlgebra.Group
         obj::T
      end

      struct $Elem{T<:AbstractAlgebra.RingElem} <: AbstractAlgebra.GroupElem
         elt::T
      end

      ==(g::$Elem, h::$Elem) = g.elt == h.elt
      ==(G::$Gr, H::$Gr) = G.obj == H.obj

      elem_type(::Type{$Gr{T}}) where T = $Elem{elem_type(T)}
      eltype(::Type{$Gr{T}}) where T = $Elem{elem_type(T)}
      parent_type(::Type{$Elem{T}}) where T = $Gr{parent_type(T)}
      parent(g::$Elem) = $Gr(parent(g.elt))
      (G::$Gr)(g::$Elem) = MltGrpElem(G.obj(g.elt))
   end
end

MultiplicativeGroup = MltGrp
AdditiveGroup = AddGrp

function (G::MltGrp)(g)
   r = (G.obj)(g)
   isunit(r) || throw(DomainError(
      "Cannot coerce to multplicative group: $r is not invertible!"))
   return MltGrpElem(r)
end

(G::AddGrp)(g) = AddGrpElem((G.obj)(g))

(G::MltGrp)() = MltGrpElem(G.obj(1))
(G::AddGrp)() = AddGrpElem(G.obj())

inv(g::MltGrpElem) = MltGrpElem(inv(g.elt))
inv(g::AddGrpElem) = AddGrpElem(-g.elt)

for (Elem, op) in ([:MltGrpElem, :*], [:AddGrpElem, :+])
   @eval begin

      ^(g::$Elem, n::Integer) = $Elem(op(g.elt, n))

      function *(g::$Elem, h::$Elem)
         parent(g) == parent(h) || throw(DomainError(
            "Cannot multiply elements of different parents"))
         return $Elem($op(g.elt,h.elt))
      end
   end
end

show(io::IO, G::MltGrp) = print(io, "The multiplicative group of $(G.obj)")
show(io::IO, G::AddGrp) = print(io, "The additive group of $(G.obj)")

show(io::IO, g::Union{MltGrpElem, AddGrpElem}) = show(io, g.elt)

gens(F::AbstractAlgebra.Field) = elem_type(F)[gen(F)]

order(G::AddGrp{<:AbstractAlgebra.GFField}) = order(G.obj)
elements(G::AddGrp{F}) where F <: AbstractAlgebra.GFField = (G((i-1)*G.obj(1)) for i in 1:order(G))

order(G::MltGrp{<:AbstractAlgebra.GFField}) = order(G.obj) - 1
elements(G::MltGrp{F}) where F <: AbstractAlgebra.GFField = (G(i*G.obj(1)) for i in 1:order(G))

length(G::Union{AddGrp, MltGrp}) = order(G)

function iterate(G::AddGrp, s=0)
   if s >= order(G)
      return nothing
   else
      g, s = iterate(G.obj,s)
      return G(g), s
   end
end

function iterate(G::MltGrp, s=0)
   if s > order(G)
      return nothing
   else
      g, s = iterate(G.obj, s)
      if g == G.obj()
         g, s = iterate(G.obj, s)
      end
      return G(g), s
   end
end
```
So that You may use `M = MltGrp(MatrixSpace(R, 1,1))`, `M()` returns `[1]` and so on

**Comment by thofma** [comment]
Sorry, I don't see the problem with `Ring` not being of subtype `Group`. To make `M = MltGrp(MatrixSpace(R, 1,1)), M()` work in your example, you just need to relax your type restrictions to `<: NCRing` and use `MatrixAlgebra(R, 1)` instead of `MatrixSpace`.

**Comment by kalmarek** [comment]
thanks for the modifications with `NCRing` and `MatrixAlgebra`

The point was that the same code could be run for both group elements and ring elements;
Now I need to do some wrapping (e.g. with `MltGrp`);
But if this is a design decision i'm fine with this.

**Comment by wbhart** [comment]
We are still discussing how groups should be done, really. I think there are two options:

1) Have Group parameterised by a symbol representing the operation (whether +, *, \circ, etc.). Have every group implement a binary function called op, which is the group operation (so that generic code can work with any group).

2) Introduce functions for turning other kinds of objects into groups, e.g. AdditiveGroupOf(F) for F a field, which would wrap a field and its elem_type automatically and make a Group and GroupElems out of them (so that functions written to work with groups will do so).

The second is probably the most flexible, but it can make performance problematic. In Singular.jl we already encounter a case where we end up needing to rewrite a generic hack of this kind in a special case because the performance was not there. On the other hand, it is easy to write specialised code for cases where generic performance is not good enough, so this is probably not a serious argument against 2.
