### ISSUE TITLE
nightly CI failures due to finalizers on `BigFloat`s

### ISSUE THREAD

**Issue by lgoettgens** [Nemocas/AbstractAlgebra.jl#1825]
Just as a heads-up and point to reference to. The issue is already reported upstream at https://github.com/JuliaLang/julia/issues/55965

**Comment by thofma** [comment]
Not sure if being mutable is part of the API. Anyway, we can adjust the test.

**Comment by lgoettgens** [comment]
According to the comment in the test file, this test should test https://github.com/JuliaLang/julia/issues/26939. But since this was about BigFloats, and BigFloats can seemingly no longer be used as keys in WeakKeyIdDicts, I think we should just remove the test

**Comment by lgoettgens** [comment]
Hmm, so https://github.com/JuliaLang/julia/pull/55906 changed the corresponding test in julia base for `WeakKeyDict` to test with BigInts rather than BigFloats (which then no longer corresponds to https://github.com/JuliaLang/julia/issues/26939...). Let's wait for an answer in the julia issue

**Comment by fingolfin** [comment]
Well we had that test in there precisely because someone was trying to use a BigFloat as a key there... the old BigFloat implementation had a bug there, which was fixed.

Perhaps WeakKeyDict and WeakKeyIdDict should be enhanced to also support immutable keys (to prevent breakage when changing the implementation of a type, like happened here).

But this all really isn't our concern: we don't use bigfloat keys in weak key (id) dicts, and frankly I don't see why anyone would. So I'd just remove the failing test and be done with this.

**Comment by fingolfin** [comment]
(Actually I am not even sure it would be possible to have WeakKeyDict work with an immutable key, but again, that's really not important for us here)
