### ISSUE TITLE
Document union types such as RingElement, FieldElement

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#208]
Currently we have

```
julia> BigInt <: AbstractAlgebra.RingElem
false
```
and thus also

```
julia> typeof(one(AbstractAlgebra.ZZ)) <: AbstractAlgebra.RingElem
false
```

however

```
julia> typeof(one(Nemo.ZZ)) <: AbstractAlgebra.RingElem
true
```
Is this intended?

**Comment by fieker** [comment]
I think it is unavoidable:
  AbstractAlgebra.ZZ -> BigInt
  Nemo.ZZ -> fmpz
We cannot make BigInt part of our hierarchy - unfortunately...
In Oscar, esentially, ZZ = FlintZZ => fmpz as it is faster.

Greetings
 Claus

**Comment by thofma** [comment]
For this reason there is `AbstractAlgebra.RingElement`.
```julia
julia> BigInt <: AbstractAlgebra.RingElement
true
```

**Comment by wbhart** [comment]
Yes, in general you can't make BigInt <: RingElem since it already belongs to Integer (a Julia defined abstract type). (A concrete type can only belong to one abstract type.)

For this reason, as Claus says, we define a union of RingElem and Integer (and a few other Julia abstract types), called RingElement, so that BigInt <: RingElement as does any RingElem type.

**Comment by wbhart** [comment]
Yes, there are a few such cases of union types that will now need to be described. You could change the name of this issue to "Document union types such as RingElement, FieldElement" [and PuisexSeriesElem, LaurentSeriesElem, PolynomialElem], so it gets done.
