### ISSUE TITLE
ResidueRing(R, 0) should throw an error

### ISSUE THREAD

**Issue by dataopt** [Nemocas/AbstractAlgebra.jl#365]
I believe, mathematically, Z/<0> is a legitimate residue ring even though it is isomorphic to Z.  However, attempting `ResidueRing(ZZ, 0)` leads to `DivideError: integer division error`.  Is there any other way to create the residue ring Z/<0>?

**Comment by wbhart** [comment]
You kind of already answered your own question.

Do you have an application for this.

**Comment by dataopt** [comment]
I want to use `invmod` for polynomials in `Z[x]`.  But `invmod` takes only polynomials over Residue Rings or a Field.  So I was hoping to coax `Z` into a residue ring so I can use `invmod`.

**Comment by wbhart** [comment]
You could just use Nemo.jl and use number fields. Technically that is Q[x],
but if the polynomial is monic over Z it's essentially doing what you want.

If you really want to use invmod for Z[x], you can just add RingElement to
the list of accepted types on lines 1029, 1153 and 2171 of
src/generic/Poly.jl, replace line 1162 with:

   binv = AbstractAlgebra.div(1, lead(g))

and then replace lines 2198 and 2199 with:

   u1 *= AbstractAlgebra.div(1, c1)
   u2 *= AbstractAlgebra.div(1, c2)

Of course it will only work if the modulus is monic. We've toyed with the
idea of supporting this, but there's not a lot of motivation given that we
have proper number fields in Nemo.

**Comment by dataopt** [comment]
Thanks for the details.

Indeed, I could use Q[x].  But I was hoping that I could give a direct illustration of what is discussed in  [Modern Computer Algebra](https://www.cambridge.org/core/books/modern-computer-algebra/DB3563D4013401734851CF683D2F03F0) regarding `invmod` for Z[x] for teaching purpose.  After all, a polynomial defined in Z[x] looks cleaner when printed than when defined in Q[x].

I sincerely hope the support for `RingElement` could be added officially as the changes you suggested seem simple enough.

**Comment by wbhart** [comment]
We'll give it some thought, but it isn't as simple as introducing the hack I mentioned, as that breaks other things. And we certainly aren't checking that the modulus is monic in that hack.

One way of introducing something similar is to allow residue rings of Z[x] mod a monic polynomial. We have discussed it at various times.

We could certainly introduce an invmod for Z[x] only (or polynomials over a ring) that checks for a monic polynomial. But not everyone agrees this should be allowed, since Z[x] is not Euclidean and invmod is supposed to only be defined for the Euclidean interface.

**Comment by dataopt** [comment]
Thanks for the insights.  I'll go for the option of overloading Generic.invmod in the meantime.

It seems to me that allowing residue rings of Z[x] mod a monic polynomial could be useful in the long run.

**Comment by wbhart** [comment]
@fieker @thofma 

Magma currently doesn't allow creation of ZZ/(0). Sage just returns ZZ (rather than a residue ring ZZ/(0)).

Do we want to allow creation of ZZ/(0)? If so, should it just return ZZ?

And by extension, when we do ResidueRing/Field(S, S(0)) for any ring S, should we:

1) just return S?
3) hack the existing ResidueRing functionality to support R/(0) by checking for modulus zero everywhere?

Of course 1 is the easiest. 2 is a bit messy but has the advantage that the result belongs to AbstractAlgebra.ResRing.

**Comment by wbhart** [comment]
Or:

3. Add a special type for such kinds of residue ring.

This has the disadvantage of not having the same type as other residue rings of the same ring S, though it can still belong to AbstractAlgebra.ResRing.
