### ISSUE TITLE
divrem for Generic.Poly

### ISSUE THREAD

**Issue by kalmarek** [Nemocas/AbstractAlgebra.jl#366]
```julia
julia> R, x = Nemo.ZZ["X"]
(Univariate Polynomial Ring in X over Integer Ring, X)

julia> AbstractAlgebra.divrem(1 - 3x + 2x^2, 2(x-1))
(X, -X+1)

julia> R, x = AbstractAlgebra.ZZ["X"]
(Univariate Polynomial Ring in X over Integers, X)

julia> AbstractAlgebra.divrem(1 - 3x + 2x^2, 2(x-1))
ERROR: MethodError: no method matching div(::AbstractAlgebra.Generic.Poly{BigInt}, ::AbstractAlgebra.Generic.Poly{BigInt})
```
is this behavior intended??

**Comment by wbhart** [comment]
I assume you did using Nemo, or something? If so then AbstractAlgebra.divrem is actually Nemo.divrem. Flint defines divrem for Z[x], but AbstractAlgebra does not. Basically it is just adding functionality, as Nemo is wont to do.

**Comment by wbhart** [comment]
The only real control you have when using functions that are overloading functions in Base is to control the type:

```
julia> using Nemo

julia>R, x = Generic.PolynomialRing(Nemo.ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> divrem(1 - 3x + 2x^2, 2(x-1))
ERROR: MethodError: no method matching div(::AbstractAlgebra.Generic.Poly{fmpz}, ::AbstractAlgebra.Generic.Poly{fmpz})
```

In other words, disambiguating doesn't do what you think it does when we are overloading a function in base.

If you call any other kind of function which is defined in Nemo but not AbstractAlgebra it works as expected:

```
julia> import AbstractAlgebra

julia> import Nemo

julia> R, x = Nemo.PolynomialRing(Nemo.ZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring, x)

julia> Nemo.factor(1-3x+2x^2)
1 * (x-1) * (2*x-1)

julia> AbstractAlgebra.factor(1-3x+2x^2)
ERROR: UndefVarError: factor not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
```

Of course, you probably expect AbstractAlgebra.PolynomialRing(Nemo.ZZ, "x") to create a generic polynomial ring over a Nemo ZZ coefficient ring, which it does not. This is because Nemo imports PolynomialRing from AbstractAlgebra and overloads it.

This is why Generic exists. Then AbstractAlgebra.Generic.PolynomialRing(Nemo.ZZ, "x") does what you want.

**Comment by wbhart** [comment]
We could change this behaviour by having Nemo define its own functions, rather than overloading AbstractAlgebra ones. But this implies having Nemo call AbstractAlgebra explicitly when it needs to construct a generic ring, e.g. a polynomial ring over a polynomial ring. That would be a lot of coding, but we could do it.

**Comment by thofma** [comment]
I don't see any problem. `divrem` has a method for one type but not for the other. It is exactly what doing what it is supposed to do. Disambiguation is working as expected.

**Comment by wbhart** [comment]
I was talking about the fact that AbstractAlgebra.divrem called the Nemo divrem, not the AbstractAlgebra one.

From the point of view of Oscar, this is more or less intended, as Nemo/AbstractAlgebra is supposed to be viewed as a single unit. But maybe someone wants something more.

The same problem exists for other packages too. But I'd recommend we only disambiguate the type constructors, as anything else will be a hell of a lot of work.
