### ISSUE TITLE
gen for vector spaces

### ISSUE THREAD

**Issue by ulthiel** [Nemocas/AbstractAlgebra.jl#571]
Why does

```
V=VectorSpace(QQ,2)
gen(V,1000)
```

work? Shouldn't this throw an error? ngens(V) gives 2.

Could we also implement V(i) or V[i] or V.i as a shortcut for gen(V,i)?

**Comment by fieker** [comment]
On Thu, Feb 06, 2020 at 03:25:44AM -0800, Ulrich Thiel wrote:
> Why does
> 
> ```
> V=VectorSpace(QQ,2)
> gen(V,1000)
> ```
> 
> work? Shouldn't this throw an error? ngens(V) gives 2.
I second that
 + basis(V) of course
> 
> Could we also implement V(i) or V[i] or V.i as a shortcut for gen(V,i)?
That as well, V[i] is what we support for abelian groups - but I'd
suggest to actually allow/ support this for all structures...
V(i) is more troublesome because it usually means
  turn i into an element
for number fields, this would be ambigous...

V.i cannt work - the julia parser is against this...

**Comment by thofma** [comment]
Yes, it should throw.

I am also in favor of `V[i] == gen(V, i)`. We have this syntax in Hecke for finitely generated abelian groups and is quite useful.

**Comment by ulthiel** [comment]
I just noticed there is also a V(vector) function, so yes, V[i] would be best.

**Comment by wbhart** [comment]
No objections to either proposal from me. The first is clearly a missing bounds check.
