### ISSUE TITLE
Change `rref(R::Ring)` to `pseudo_rref(R::Ring)`

### ISSUE THREAD

**Issue by thofma** [Nemocas/AbstractAlgebra.jl#684]
At the moment it is impossible to write generic code for rings which uses `rref`, because the behavior for things of type `Ring` and `Field` is inconsistent. So one always has to write two versions, which defeats the purpose of using julia and having `Ring <: Field`.

I propose to deprecate the current `rref(R::Ring)` and introduce `pseudo_rref(R::Ring)`, similar to `pseudo_inverse`. @wbhart mentioned this already in https://github.com/Nemocas/AbstractAlgebra.jl/pull/683.

**Comment by wbhart** [comment]
Fine by me.

We also have solve_ff which dispatched to can_solve_with_solution_fflu. But I am not sure what the equivalent for can_solve_with_solution_lu is. Perhaps we should now introduce something for symmetry reasons. On the other hand, I guess you would want pseudo_solve.

It's getting to be a bit of a mess though. We also have solve_rational and solve_ringelem, one of which dispatches to the other.

**Comment by thofma** [comment]
I don't mind the prefix/suffix. For the functions you listed, you get the same return types for arguments over `Field` or `Ring`?

At the moment
```julia
function f(A::MatElem{<:RingElement})
  x = rref(A) # do something with x
```
is always broken and requires special attention for the field case.

**Comment by wbhart** [comment]
Well, solve_ff over a field does divide by the denominator at the end, so you don't get the extra d parameter. The version over a ring returns the d.

solve_rational{RingElement} and solve_ringelem{RingElement} do exactly the same thing, namely call solve_ff{RingElement}, except over a polynomial ring. This will return the denominator.

solve{FieldElement} calls solve_ff{FieldElement}.

I'm not sure if we should remove solve_ff, which just does the denominator division when called over a field, or if we should remove solve_ringelem, which just seems to act as a common wrapper for solve_ff but otherwise doesn't do anything. It's just factoring out three or four lines of code which just check the input of solve_ff.

**Comment by fieker** [comment]
On Thu, Nov 05, 2020 at 01:10:43AM -0800, wbhart wrote:
> Well, solve_ff over a field does divide by the denominator at the end, so you don't get the extra d parameter. The version over a ring returns the d.
> 
> solve_rational{RingElement} and solve_ringelem{RingElement} do exactly the same thing, namely call solve_ff{RingElement}, except over a polynomial ring. This will return the denominator.
> 
> solve{FieldElement} calls solve_ff{FieldElement}.
> 
> I'm not sure if we should remove solve_ff, which just does the denominator division when called over a field, or if we should remove solve_ringelem, which just seems to act as a common wrapper for solve_ff but otherwise doesn't do anything. It's just factoring out three or four lines of code which just check the input of solve_ff.
> 

To me, the "best" interface we can come up with, for as much generic as
possible is probably euclidean rings
 - this includes all fields
 - Z, k[x]
 - localisations of those rings
 - completions (pAdic, qAdic, power series, ...)
 - and some outliers

For those we could do "everything" generically while still allowing for
special algorithms.
  rref(field) -> Gauss/ LU, so triangular plus transformation (if
  desired)
  rref(ring) -> hnf so triangular plus triangular (if desired)
    A bonus: every field is (mathemtically) euclidean and hnf would just
    do Gauss.
  using divrem (which for fields returns diveact, 0), gcd, ... one can
  write generic stuff that would work in all cases

For "all" other rings, you need different technology: mpoly -> Groebner,
Dedekind -> pseudo stuff ala Cohen, research level in general

the pseudo versions returning a denominator are difficult, they work
implicitly over the quotient field hence for many applications solve an
essentially unrelated problem.

So I'd
 - call the current rref(Ring) rref_rational or pseudo_rref or s.th.
   similar
 - for euclidean rings, rref -> hnf
 - have an inspiration how to achieve the dispatch to the different
   algorithms elegantly
 - try to figure out the hierarchy of lin. alg: if I want to add
   performance for a new ring (say number field), which functions do I
   need to supply minimally so that as many as possibly other functions
   benefit?
   e.g. is everything at the end based on rref (with some flags), then
   I'd supply this and let the generic handle things
   or maybe its sovlve that is at the core....

**Comment by thofma** [comment]
Thanks for the clarification @wbhart. Indeed this could also be clean up a bit as you described and maybe even some more as Claus wrote.

I will deprecate `rref` to `rref_rational` (which can be discovered easier than `pseudo_rref`) and is in line with the `*_solve_*` functions.

**Comment by wbhart** [comment]
Should we then move to inv_rational?

**Comment by wbhart** [comment]
@fieker I am not convinced yet that we need to restrict to Euclidean rings. I think so long as there is an effective gcd then we are ok. E.g. Z[x] has a gcd, but is not Euclidean.

The literature on this stuff is opaque, as I found out when I did minpoly.

**Comment by wbhart** [comment]
Also, for some rings one has an exact division but not a divrem. So I think we can do more general stuff if we don't rely on divrem.

**Comment by wbhart** [comment]
To be clear: the pseudo versions are for very fast code over fraction fields. They don't serve a purpose on their own, but for example solve_ff (which is used for actual fields) calls the pseudo version.

**Comment by thofma** [comment]
(From my limited experience, I think that `gcdx` is as important as `gcd` in the algorihtms, which would rule out Z[x], but include principal ideal domains.)

I am happy to have the `pseudo_`/`_rational` versions around. I can also make the change `pseudo_inv` -> `inv_rational`, since we seem to agree to prefer `rational` over `pseudo`?

**Comment by fieker** [comment]
On Thu, Nov 05, 2020 at 01:38:51AM -0800, wbhart wrote:
> To be clear: the pseudo versions are for very fast code over fraction fields. They don't serve a purpose on their own, but for example solve_ff (which is used for actual fields) calls the pseudo version.
Agreed and understood.

**Comment by wbhart** [comment]
I'm currently working towards everything being based on can_solve_with_solution as previously discussed.

That seems reasonable to me, except I haven't figured out how to do non-square solve_with_det (I saw your post on this elsewhere, thanks).

**Comment by wbhart** [comment]
I prefer pseudo to rational. But it's not for any particular reason. Go ahead and make the change you want. I can live with that. It's not so important to me.

**Comment by fieker** [comment]
On Thu, Nov 05, 2020 at 01:37:15AM -0800, wbhart wrote:
> Also, for some rings one has an exact division but not a divrem. So I think we can do more general stuff if we don't rely on divrem.
> 
all the HNF based stuff can be made to work for PIRs as long
as yo have constructive gcdx, you're fine.
The divrem is used in HNF, to instill some uniqueness, for general PIRs
it is not clear how to normalize gcd's and how to choose coset reps - if
you want uniqueness.
If you don't, then divrem is not neccessary

**Comment by wbhart** [comment]
The main reason is because we already have pseudodiv, pseudorem, pseudodivrem for Poly.jl, which is a standard name in the literature. It's not quite the same thing, but exists for the same reason from a certain point of view.

**Comment by wbhart** [comment]
We might be talking at cross purposes here. I think @fieker is:

1) trying to come up with the most general ring for which we can implement "everything".

2) looking for a minimal set of functions that will serve as an interface that people will have to implement.

My perspective is slightly different. I believe:

* some (maybe not all) linear algebra is possible over gcd domains if one has an effective gcd
* other rings have fraction free algorithms to avoid gcd's in rational functions (the speedup is a factor of a million or billion); here exact division only is required, not divrem
* other rings even have division free algorithms (though mainly determinant, I think)

Whether you think of these as special cases for certain types of rings, or a generalisation of part of that interface I don't know. There is an element of research here. E.g. two of the algorithms I implemented in the last few days are not from the literature.

Either way, I am currently thinking of can_solve_with_solution as being a common interface level. I've had to think really, really hard to do this (and I've certainly made compromises to do so), so I hope the goalposts won't get moved now, at least not until I've finished this tranche of changes!

One final comment: I get that you want everything to be written in terms of rref and hnf. I can see why. My counterargument is that over a field, matrix decompositions are more fundamental. (Who knows, maybe there is also something better in the ring case than hnf. I'm not working on trying to find such a thing. But other than symmetry, I see no reason to reduce everything to rref in the field case. There are at least some special cases where you should not do this.)

I am ok with there being *an* interface at the rref level, so that if someone implements rref then everything over a field Just Works. But that is a different question to whether it should be the *only* interface.

**Comment by wbhart** [comment]
Another point worth considering: originally the fraction free approach was implemented for fraction fields, but we found other fields for which solve_ff is faster, so it is actually called for all fields currently (as it didn't seem to hurt in other cases). This probably needs more care and benchmarking, but the fraction free approaches, which we now have for non-square matrices due to can_solve_with_solution_fflu, are probably more widely useful.

Of course we are a long way from anything really good. We don't currently reduce to matrix multiplication. A divide and conquer fflu for non-square matrices would currently be a research problem. But a fraction free rref handling non-square matrices and using matrix multiplication probably is also.

**Comment by wbhart** [comment]
Anyhow, I intend to provide some benchmarks so that we have some actual data to look at. But I need to get the implementation done first. One or two more days I *might* have a solve_interpolate working in the non-square case.

Unfortunately I think I may have overlooked an opportunity for optimisation in the case where n > rank in our mxn matrices, so how much benchmarks will really show at this point, I am not sure.

I also need to understand why Nemo/Flint used to be faster, but is now slower than AbstractAlgebra in some cases.

My main aim is to get to the point where we can do:

* solve over rings and fields
* non-square and singular matrices
* no performance regression in the cases for which we already have benchmarks and special algorithms implemented (division free, fraction free, interpolation)

We also need to then do:

* left and right
* make similar improvements to Flint/Nemo
* space of solutions as opposed to just a single solution
* interfaces
* reducing to (fast) multiplication

We have a *long* way to go!! But the first list above will make everything usable whilst retaining the improvements we have already made previously.

**Comment by fieker** [comment]
I thought that the (generically) (useful) factorisations compute an rref
- possibly with the wrong normalisation (upper vs lower triangular), but
they will find a rref. So to me, that's more a question of algorithmic
choice for rref then anything else...

**Comment by wbhart** [comment]
Yes, it gives you the rref. But rref doesn't give you the transform without
adjoining an identity matrix before calling it, it can't be done with
transform in-place in the original matrix, it requires constructing a new
matrix twice the original size, etc.

It's just an algorithmic choice, but it has advantages over forcing
everything via the superfluous rref.

**Comment by wbhart** [comment]
By my timing, Generic.lu is currently around 3x faster than Generic.rref(hcat(N, I)). Of course if you only need the rref and not the transform, rref will likely be faster.

**Comment by fieker** [comment]
On Thu, Nov 05, 2020 at 03:12:08AM -0800, wbhart wrote:
> Yes, it gives you the rref. But rref doesn't give you the transform without
> adjoining an identity matrix before calling it, it can't be done with
> transform in-place in the original matrix, it requires constructing a new
> matrix twice the original size, etc.
> 
> It's just an algorithmic choice, but it has advantages over forcing
> everything via the superfluous rref.

In my context, the second matrix is never a problem. On the contrary,
last week I discovered that one cannot use rref/solve/inv on imutable matrices as
every version is inplace...copy followed by inplace.

In Flint this makes total sense. In Julia: I don't know, but as a
summary
 - we will have rref
 - we wil have lu
 - plus a range of others
 - there is/ will be a hopefully optimal path to traverse here so that
   as many functions as possible can be as optimal as possible be
   written in as few functions as possible
   PLUS many optimised special cases.

 none of this actually is in conflict. Generic implementations are
 almost never as fast as specific ones - but frequently good enough.
 Having several generic methods allows one to choose....
