### ISSUE TITLE
Type stable creation of arrays of zeroes (is the `zero` and `zeros` interface not implemented)?

### ISSUE THREAD

**Issue by Krastanov** [Nemocas/AbstractAlgebra.jl#704]
I would like to be able to create an array of zeroes inside of a function while ensuring the element type of the array is as specific as possible, depending on the type of an input argument for the function. I did the following:

```
function f(; arg=1.0)
    temporary_array = zeros(typeof(arg), 5)
    ...
end
```

However, this does not work with symbolic expressions from `AbstractAlgebra`. I was hopeful to do the following

```
R, (e,) = PolynomialRing(RealField, ["e"])
f(arg=e)
```

But it does not work due to zeros not being implemented.

I tried the following code:

```
using AbstractAlgebra
R, (e,) = PolynomialRing(RealField, ["e"])
zero(e) # works as expected
R(0) # works as expected
zeros(typeof(e),4) # fails, while I expected it will return [R(0), R(0), R(0), R(0),]
zero(typeof(e)) # fails, while I expected it will return R(0)
```

I saw that the type structure of Nemo is different than usual (https://nemocas.github.io/AbstractAlgebra.jl/latest/types/), but I do not think it helped me find a solution. 

**I am not certain how to proceed in a way that creates efficient Float64 array of zeroes when the default arg is used, but successfully creates an array of symbolic zeros when an AbstractAlgebra object is given.**

**Comment by thofma** [comment]
The problem is that the type of the element or ring does not have enough information to create the zero. The problem is that `PolynomialRing(RealField, ["e"])` and `PolynomialRing(RealField, ["e", "f"])` both have the same type. So it is not possible to determine the zero just from the ring type or the element type. This is a quite severe limitiation in the linear algebra code of julia itself, which comes up on a regular basis.

You could try replacing your `zeroes(typeof(arg), 5)` call by `fill(zero(arg), 5)`.

**Comment by thofma** [comment]
@Krastanov I assume this solved your problem. If you have more usability questions, you can also ask them on discourse.
