### ISSUE TITLE
Document minimal example of a ring in Interfaces

### ISSUE THREAD

**Issue by wbhart** [Nemocas/AbstractAlgebra.jl#934]
People who want to implement their first ring satisfying the AbstractAlgebra Ring Interface have asked for a minimal example that they can cut and paste from.

**Comment by 8d1h** [comment]
That would be great!

Also I'd suggest a reminder: if one implements a ring element type with parent as a field
```julia
mutable struct MyRingElem <: RingElem
   parent::MyRing
   x
   ...
end
```
we need to redefine `deepcopy(::MyRingElem)` to *not* make a deep copy for the parent, otherwise some constructions will not work, e.g. polynomial rings over `MyRing` (I spent a lot of time debugging this...).

**Comment by wbhart** [comment]
We should add that to the interface docs. Agreed. Thanks for the comment.
