### ISSUE TITLE
Generic.SeriesElem normalisation

### ISSUE THREAD

**Issue by fieker** [Nemocas/AbstractAlgebra.jl#940]
```
julia> K, a = quadratic_field(-1)
(Imaginary quadratic field by x^2 + 1, sqrt(-1))

julia> S, t = PowerSeriesRing(K, 2, "t")
(Univariate power series ring in t over K, t + O(t^3))

julia> S([1, 0], 2, 4, 0)
1 + O(t^4)

julia> isone(ans)
false
```

is this deliberate or an error? The problem is that the Array passed in has trailing 0s that are not removed...

**Comment by wbhart** [comment]
Try

```
S([1, 0], 1, 4, 0)
```

The documentation does explain this. Trailing zeros are allowed but only the first len coefficients are considered.

**Comment by wbhart** [comment]
Admittedly it would be more appealing to the user to have a constructor that took the length from the array and then automatically normalised. I thought about adding such a constructor, as the current ones were originally meant to be internal, where you really want to be able to add trailing zeros (coefficients that you are about to fill in).

Back in the early days it was very hard to deal with undefined references, which is why it was done this way.

**Comment by fieker** [comment]
It works as in renormalizing for fmpq, but fails generically. I solved my
instance by removing trailing zeros, but was wondering...
If this is as planned, let's close the issue

**Comment by wbhart** [comment]
fmpq uses flint, which automatically normalises everything in sight agressively.
