### ISSUE TITLE
exps of zero MPoly

### ISSUE THREAD

**Issue by heiderich** [Nemocas/AbstractAlgebra.jl#99]
What should the output of `f.exps` be if `f` is an MPoly that is zero? I am surprised by the output in the following example:

```
julia> using AbstractAlgebra

Welcome to AbstractAlgebra version 0.0.8

AbstractAlgebra comes with absolutely no warranty whatsoever


julia> R,vars_R = PolynomialRing(QQ,["x"]);

julia> x = vars_R[1]
x

julia> f = 0*x
0//1

julia> f.exps
1×1 Array{UInt64,2}:
 0x0000000000000003

```

**Comment by wbhart** [comment]
f.exps is not a documented interface. It's just an array used to store
exponents, and could contain anything past the current number of terms of
the polynomial. We don't resize it, I think.

But as I said, this is not the way to access exponents (the current order
of terms needs to be reversed anyway, so it's currently wrong regardless).
We need to design an interface for accessing exponents. In fact there will
be two interfaces, one for polynomials which only define an iterator
(because they are implemented as linked lists), and one for polynomials
that have random access to terms (because they are implemented as an array).

I assume both interfaces will allow iteration over all exponents.

I'm not at all keen on defining random access to polynomials implemented as
linked lists, but I notice this has already happened in Singular.jl. The
problem with implementing it is that people will use it without realising
it is totally inefficient and will blow the complexity of their algorithms
up.

**Comment by heiderich** [comment]
Thanks for this explanation.
